import getpass

def create_env_file():
    """
    Interactively prompts the user for email configuration and creates a .env file.
    """
    print("--- Safecast API Server Setup ---")
    print("Please provide your SMTP email configuration.")

    mail_username = input("Enter your MAIL_USERNAME: ")
    mail_password = getpass.getpass("Enter your MAIL_PASSWORD: ")
    mail_from = input("Enter your MAIL_FROM address: ")
    mail_server = input("Enter your MAIL_SERVER (e.g., smtp.gmail.com): ")
    mail_port = input("Enter your MAIL_PORT (e.g., 587): ")

    env_content = f"""# Email configuration generated by setup.py
MAIL_USERNAME={mail_username}
MAIL_PASSWORD={mail_password}
MAIL_FROM={mail_from}
MAIL_SERVER={mail_server}
MAIL_PORT={mail_port}
MAIL_STARTTLS=True
MAIL_SSL_TLS=False
"""

    try:
        with open(".env", "w") as f:
            f.write(env_content)
        print("\n.env file created successfully!")
        print("You can now start the server with 'uvicorn app.main:app --reload'")
    except IOError as e:
        print(f"\nError: Failed to write to .env file: {e}")

if __name__ == "__main__":
    create_env_file()
